oauth-xx/oauth-ruby

lib/oauth/cli.rb
```shell
usr/lib64/ruby/gems/1.8/gems/oauth-0.4.7/lib/oauth/cli.rb:110:in `execute': undefined method `downcase' for :post:Symbol (NoMethodError)
from /usr/lib64/ruby/gems/1.8/gems/oauth-0.4.7/lib/oauth/cli.rb:19:in `execute'
from /usr/lib64/ruby/gems/1.8/gems/oauth-0.4.7/bin/oauth:5
from /usr/bin/oauth:23:in `load'
from /usr/bin/oauth:23
```
make sure the `options[:method]` is converted to a string before using downcase
=> undefined method `downcase' for :post:Symbol (NoMethodError)

lib/oauth/helper.rb
Previously, if an Oauth code path was executed in a Rails controller, it would result in these `to_s` methods to return an ActiveSupport::SafeBuffer object, rather than String - which causes problems in the URI library and ends up raising an error.
This change should be also be compatible with non-Rails environments as well:
irb(main):001:0> ActiveSupport::SafeBuffer.new("foo").to_s.to_str.class
=> String
irb(main):002:0> String.new("bar").to_s.to_str.class
=> String
irb(main):003:0> nil.to_s.to_str.class
=> String
=> Rails 3+ / ActiveSupport::SafeBuffer patch

lib/oauth/cli.rb
There are two fixes:
* Syntax for optional arguments had changed, so --version was always evaluated as the version command, which completely broke the switch for specifying the oauth version
* The scope option caused an exception deeper in the code, because it was nill if not specified, which eg. Net::HTTP::GET couldn't handle.
=> Fix oauth cli option parser on Ruby 2.2

lib/oauth/client/helper.rb, lib/oauth/client/net_http.rb, lib/oauth/consumer.rb, test/test_consumer.rb, test/test_net_http_client.rb
While updating integration code I ran into some trouble with oauth requests returning 500, which I traced back to the inclusion of `oauth_body_hash` in the access token request. 
The [specs here](http://oauth.googlecode.com/svn/spec/ext/body_hash/1.0/oauth-bodyhash.html#when_to_include) indicate, that while it's not quite criminal, it could cause some api's to reject the request. So I pulled it out, just to see what would happen, and the request was successful.
I wasn't able to locate an existing solution or work around for this.
=> Fix token requests do not include oauth_body_hash

lib/oauth/consumer.rb
On some systems certificate file could be placed in different directories. That could cause unexpected errors. Added usage of environment variable and one more file path, used in centos.
=> added possible paths for cert files

lib/oauth/tokens/token.rb
`Token.to_query()` uses the nonstandard `oauth_secret` key. I changed this to `oauth_token_secret` to match the [OAuth Spec](http://oauth.net/core/1.0/#rfc.section.6.1.2).
With this change, `Token.to_query()` returns a valid response for a token request.
=> Change oauth_secret to oauth_token_secret

lib/oauth/signature/base.rb, test/test_signature_hmac_sha1.rb
The `OAuth::Signature::Base#==` method currently incorrectly returns `true` even when the signature from the request does not match. See e.g. the test case in this pull request, the correct signature is `xcHYBV3AbyoDz7L4dV10P3oLCjY=` and current implementation verifies a different signature `xcHYBV3AbyoDz7L4dV10P3oLCjZ=` as also correct. This may be a security risk for OAuth servers using the `OAuth::Signature::Base#==` or `OAuth::Signature::Base#verify` methods to verify signatures submitted by clients.
Problem goes away when comparing the signatures instead of comparing the results of `Base64.decode64(signature)`.
=> Correct verify

lib/oauth/tokens/request_token.rb
URI::Generic.query defaults to nil if there is no query part in the parsed
string, so make sure we don't call methods on nil.
This fixes the already existing request_token tests of which 3/5 are
failing with:
> NoMethodError: undefined method `blank?' for nil:NilClass
=> fix regression by guarding against URI::Generic.query being nil

lib/oauth/tokens/request_token.rb
`build_authorize_url` tried to invoke a method called `blank?` against `uri.query` , apparently trying to guard against the empty string. Although `blank?` is defined for strings in Rails, it is not defined in stock Ruby, causing `build_authorize_url` to fail.  I fixed the problem by converting the query string to a Hash object using the standard library, rather than trying to manually manipulate the query string.
=> Fixed broken method.

lib/oauth/request_proxy/action_controller_request.rb, lib/oauth/request_proxy/base.rb
Running a small app I was getting a `NoMethodError: undefined method 'blank?' for nil:NilClass`. Adding a `require 'active_support/core_ext/object/blank'` would fix it, I guess it's a hidden dependency, not surfaced by the tests because ActiveSupport is a development dependency.
A possible solution is adding that dependency, but there are only two instances of `blank?` so I thought it would be better to just replace the call with the equivalent implementation.
Note 1: ActiveSupport's `blank?` also checks for `nil?` but in this two cases it is guaranteed to be a `String` (one is called on the items returned by `String#split`, the other one on `Rack::Request#query_string` which ends up with a `#to_s`).
Note 2: <s>Not sure if this is a duplicate of #108.</s> No, I don't think so. I *think* …
=> Replace String#blank? with its implementation

README.rdoc
Storing variables in sessions is not the proper way. 
Updating to store only token and secret in session.  Code is tested.
=> Update README.rdoc to store tokens in session

test/cases/oauth_case.rb
Silencing 'oauth-ruby/test/cases/oauth_case.rb:9: warning: instance variable @method_name not initialized'
=> Silencing a warning for ivar not initialized

lib/oauth/request_proxy/base.rb
Silencing 'oauth-ruby/lib/oauth/request_proxy/base.rb:79: warning: extra states are no longer copied: <list>'
=> Silencing a warnign in Hash.reject

lib/oauth/client/action_controller_request.rb, lib/oauth/client/em_http.rb, lib/oauth/client/net_http.rb
```
/Users/tj/github/opensource/oauth-ruby/lib/oauth/client/net_http.rb:2: warning: loading in progress, circular require considered harmful - /Users/tj/github/opensource/oauth-ruby/lib/oauth/client/helper.rb
from /Users/tj/.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in  `<main>'
from /Users/tj/.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:4:in  `select'
from /Users/tj/.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:15:in  `block in <main>'
from /Users/tj/.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb:15:in  `require'
from /Users/tj/github/opensource/oauth-ruby/test/integration/consumer_test.rb:1:in  `<top (required)>'
from /Users/tj/github/opensource/oauth-ruby/test/integration/consumer_test.rb:1:in …
```
=> Silencing 'loading in progress, circular require considered harmful'

lib/oauth/core_ext.rb
turns out ActiveSupport is a mandatory dependency and camelize was included there
=> Undo adding String#camelize

lib/oauth/consumer.rb
=> Silencing 'Net::HTTPResponse#header is obsolete'

.travis.yml, Gemfile, HISTORY, oauth.gemspec, test/test_helper.rb, test/test_helper_units.rb, test/units/test_access_token.rb, test/units/test_action_controller_request_proxy.rb, test/units/test_cli.rb, test/units/test_consumer.rb, test/units/test_curb_request_proxy.rb, test/units/test_em_http_client.rb, test/units/test_em_http_request_proxy.rb, test/units/test_hmac_sha1.rb, test/units/test_net_http_client.rb, test/units/test_net_http_request_proxy.rb, test/units/test_oauth_helper.rb, test/units/test_rack_request_proxy.rb, test/units/test_request_token.rb, test/units/test_rest_client_request_proxy.rb, test/units/test_rsa_sha1.rb, test/units/test_server.rb, test/units/test_signature.rb, test/units/test_signature_base.rb, test/units/test_signature_hmac_sha1.rb, test/units/test_signature_plain_text.rb, test/units/test_token.rb, test/units/test_typhoeus_request_proxy.rb
- Adding support to Ruby 2.4 and head
- Upgrading to CodeClimate 1.0
- Nokogiri 1.7 does not accept Ruby 2.0
- TravisCI no longer needs libcurl-dev
- minor cleanup on tests
=> Upgrade Code Climate and fixing tests

lib/oauth/cli/base_command.rb, test/units/test_cli.rb
Just what it says on the tin ^
=> Fix typo in CLI docs 'none' -> 'nonce'

README.rdoc
I felt this step was missing when trying to make my first requests using this gem, so I added it - I think it will help out people new to this project.
=> Add `require 'typhoeus'` to README.rdoc

lib/oauth/consumer.rb, lib/oauth/tokens/request_token.rb, lib/oauth/version.rb, test/units/test_request_token.rb
Solve issue https://github.com/oauth-xx/oauth-ruby/issues/161
1. Adds authenticate_url methods.
2. Bumps version number
I did some testing and it works.
Very simple code to verify:
```ruby
#!/usr/bin/ruby
require 'oauth'
require 'sinatra'
CONSUMER_KEY = ENV['CONSUMER_KEY']
CONSUMER_SECRET = ENV['CONSUMER_SECRET']
raise 'Missing Consumer' if CONSUMER_KEY.nil? || CONSUMER_SECRET.nil?
set :port, 8000
set :bind, '0.0.0.0'
consumer = OAuth::Consumer.new(CONSUMER_KEY, CONSUMER_SECRET, site: 'https://api.twitter.com')
get '/' do
"Hello World!"
end
get '/register' do
request_token = consumer.get_request_token oauth_callback: 'https://twitter-test.agora-security.com/auth/twitter/callback'
redirect request_token.authorize_url
end
get '/login' do
request_token = consumer.get_request_token …
```
=> Implement authenticate_url

.travis.yml, lib/oauth/consumer.rb, oauth.gemspec, test/units/test_consumer.rb
Should _only_ use no_verify when no_verify: false is passed as an option to  OAuth::Consumer.new
=> Avoid using ssl no verify

.travis.yml, oauth.gemspec
After 1.1.0, there's an issue with how mocha is used in the codebase.
=> Fix mocha version

lib/oauth/client/helper.rb, lib/oauth/version.rb, test/units/test_client_helper.rb
Some implementations sign the payload with empty parameters.
As a result, since the library filters out any empty parameters, it couldn't be used to generate the expected signature.
This attempts to imitate the following statement from postman:
https://www.getpostman.com/docs/v6/postman/sending_api_requests/authorization
> Note: Some implementations of OAuth 1.0 require empty parameters to be added to the signature. 
> You can select “Add empty parameters to signature” to add empty parameters.
=>  Allow empty parameters.

lib/oauth/consumer.rb, test/units/test_consumer.rb
When the response returns a redirect with a location that has a different host, but the path is still the same an error was thrown.
In the case of a change of host however, we do want to continue with a new request. The site and http object have to be updated with the new host url and a new request can be made.
=> allow a redirect with different host, but same path

lib/oauth/consumer.rb
From the Net::HTTP Class, the default values are:
- `read_timeout`: 60 (seconds) [document](https://ruby-doc.org/stdlib-2.6.5/libdoc/net/http/rdoc/Net/HTTP.html#read_timeout-attribute-method)
- `open_timeout`: 60 (seconds) [document](https://ruby-doc.org/stdlib-2.6.5/libdoc/net/http/rdoc/Net/HTTP.html#open_timeout-attribute-method)
Or, is there any specific reason this library wants to set 30 seconds over that default values?
=> increase default timeout to 60 seconds

HISTORY, oauth.gemspec
I've received an update of `oauth` gem in some of my project viad dependabot, and it's shown no changelog, no official repo, no commit history or any useful info
I got to [rubygems](https://rubygems.org/gems/oauth/versions/0.5.1) page and see there is no metadata in right column:
Adding metadata in gemfile will result something like this:
=> Add metadata to gemspec file

lib/oauth.rb, lib/oauth/signature/hmac/sha256.rb, test/units/test_hmac_sha256.rb, test/units/test_signature_hmac_sha256.rb
I've had a requirement to start using HMAC-SHA256 on a project and thought it would be useful to push upstream. I've based the implementation directly on that of HMAC-SHA1.
Please let me know if this is wanted, or if I missed a test file (I took a look though and duplicated the ones I thought were necessary).
=> Add `OAuth::Signature::HMAC::SHA256` and associated tests

lib/oauth/request_proxy/action_controller_request.rb, test/units/test_action_controller_request_proxy.rb
Most of the other request proxies support PUT
requests and we need this gem to also support it
for Action Controller. This addresses issue #180
It includes the modified Action Controller proxy
and fixes the tests.
=> Action Controller support for PUT requests

CHANGELOG.md, lib/oauth/helper.rb, test/units/test_oauth_helper.rb
Signed-off-by: Peter Boling <peter.boling@gmail.com>
Closes #80
=> ✨ Handle a nested array of hashes in OAuth::Helper.normalize

.travis.yml, lib/oauth.rb, test/integration/consumer_test.rb, test/units/test_em_http_client.rb, test/units/test_net_http_client.rb, test/units/test_signature_plain_text.rb
For some reason the plaintext signature class is not `require`'d by default, and cannot be used without explicitly requiring it. This has historically been so, and the tests go out of their way to manually require the class: https://github.com/oauth-xx/oauth-ruby/blob/705ae93/test/units/test_net_http_client.rb#L28. I have no idea why this choice has been made.
Last year in issue #76 some users bumped their head against this. This should either be documented, or the class should just be required.
This pull request adds the require statement and removes all the require statements from the tests.
I also modified travis.yml to use a specific rubygems version, because master is probably broken (https://github.com/rubygems/rubygems/issues/1679) and it can break in the future. The Travis CI …
=> Require plaintext signature method

CHANGELOG.md, lib/oauth/client/net_http.rb, lib/oauth/consumer.rb, test/units/test_net_http_client.rb
Not all OAuth 1.0 implementations recognize or respect `oauth_body_hash` in the base signature for POST/PUT payloads that are not url-encoded. Provides simple mechanism to disable this feature for improved compatibility.
=> Option to disable oauth_body_hash computation

README.md
The present link seems false, as it links to the oauth version 1 gem.
=> Fix link to oauth2 gem repository
